version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: YuriPetukhov
      POSTGRES_PASSWORD: YuriPetukhov
      POSTGRES_DB: token_security
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql